### ISSUE TITLE
Space character missing

### ISSUE THREAD

**Issue by jrfbz-adhoc** [adhocteam/uswds_nextjs_starter#22]
![image](https://user-images.githubusercontent.com/128832918/228576508-e37c3c41-763c-4762-a904-327502e5a5bf.png)

Between the two sentences at the very footer of the page.

**Comment by llimllib** [comment]
Thank you!

**Comment by llimllib** [comment]
Fixed in [926efd8](https://github.com/adhocteam/uswds_nextjs_starter/commit/926efd81d47bcdcac453c906a91c47d66479e582)

**Comment by jfriedrich-va** [comment]
what service!
